# ---------- Essential -----------
[[plugins]] # plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # most recent use
repo = 'Shougo/neomru.vim'

# ---------- Useful plugins ----------
[[plugins]] # smart f
repo = 'rhysd/clever-f.vim'

[[plugins]] # smart f
repo = 'tpope/vim-repeat'

# [[plugins]] # add text object
# repo = 'kana/vim-textobj-user'
# hook_add = 'source ~/.vim/rc/plugins/vim-textobj-user.vim'

[[plugins]] # add vim operator
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
    xmap <CR> <Plug>(LiveEasyAlign)
'''

[[plugins]] # bracket completion
repo = 'cohama/lexima.vim'
hook_add = '''
    let g:lexima_map_escape = 'jj'
'''

[[plugins]] # bracket completion
repo = 'jiangmiao/auto-pairs'
hook_add = '''
  inoremap <silent> <C-l> <C-g>u<C-r>=AutoPairsFastWrap()<CR>
  let g:AutoPairsMapCh = 0
'''

[[plugins]] # faster jk
repo = 'rhysd/accelerated-jk'
hook_add = '''
    nmap <silent>j <Plug>(accelerated_jk_gj)
    nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]] # linter
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_set_highlights = 0
    " エラー行に表示するマーク
    let g:ale_sign_error = '✗'
    let g:ale_sign_warning = '⚠'
    highlight link ALEErrorSign ErrorMsg
    highlight link ALEWarningSign Search
    " エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
    let g:ale_echo_msg_format = '[%linter%] %code: %%s [%severity%]'
    " エラー表示の列を常時表示
    let g:ale_sign_column_always = 1
    " ステータスラインに情報を表示
    let g:ale_statusline_format = [
   \   g:ale_sign_error . ' %d',
   \   g:ale_sign_warning . ' %d',
   \   '✓']

    " ファイルを開いたときにlint実行
    let g:ale_lint_on_enter = 1
    " ファイルを保存したときにlint実行
    let g:ale_lint_on_save = 1
    " 編集中のlintはしない
    let g:ale_lint_on_text_changed = 0
    " 有効にするlinter
    let g:ale_linters = {
   \   'sh': ['language_server'],
   \   'cpp': ['cpplint'],
   \   'python': ['flake8'],
   \}

    " ファイルを保存したときにfix実行
    let g:ale_fix_on_save = 1
    " 有効にするfixer
    let g:ale_fixers = {
   \   '*': ['remove_trailing_lines', 'trim_whitespace'],
   \   'cpp': ['clangd'],
   \   'python': ['black'],
   \}

    " 'python': ['nayvy#ale_fixer','black'],

    " 各ツールの実行オプションを変更してPythonパスを固定
    let g:ale_python_flake8_executable = g:python3_host_prog
    let g:ale_python_flake8_options = '-m flake8'
    let g:ale_python_black_executable = g:python3_host_prog
    let g:ale_python_black_options = '-m black'
'''

[[plugins]]
repo = 'tyru/columnskip.vim'
hook_add = '''
  nmap sj <Plug>(columnskip-j)
  nmap sk <Plug>(columnskip-k)
  omap sj <Plug>(columnskip-j)
  xmap sk <Plug>(columnskip-k)
  xmap sj <Plug>(columnskip-j)
  omap sk <Plug>(columnskip-k)
'''

[[plugins]]
repo = 'kana/vim-niceblock'
hook_add = '''
    xmap I  <Plug>(niceblock-I)
    xmap A  <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
hook_add = '''
    nmap R <Plug>(operator-replace)
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
hook_add = '''
    nmap <silent>sa <Plug>(operator-surround-append)a
    nmap <silent>sd <Plug>(operator-surround-delete)a
    nmap <silent>sr <Plug>(operator-surround-replace)a
'''

[[plugins]]
repo = 'osyo-manga/vim-jplus'
hook_add = '''
    nmap J <Plug>(jplus)
'''

[[plugins]] # commentout
repo = 'tyru/caw.vim'
hook_add = '''
    let g:caw_no_default_keymappings = 1
    let g:caw_dollarpos_sp_left = ' '
    nmap <silent> gc <Plug>(caw:hatpos:toggle)
    nmap <silent> ga <Plug>(caw:dollarpos:comment)
    nmap <silent> go <Plug>(caw:jump:comment-next)
    nmap <silent> gO <Plug>(caw:jump:comment-prev)
    xmap <silent> gc <Plug>(caw:hatpos:toggle)
    xmap <silent> ga <Plug>(caw:dollarpos:comment)
    xmap <silent> go <Plug>(caw:jump:comment-next)
    xmap <silent> gO <Plug>(caw:jump:comment-prev)
'''
