[[plugins]] # plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # colorscheme
repo = 'altercation/vim-colors-solarized'
hook_add = '''
    set background=dark
    autocmd MyAutoCmd VimEnter * nested colorscheme solarized
'''

[[plugins]] # enhance statusline
repo = 'itchyny/lightline.vim'
hook_add = '''
    set laststatus=2
    set t_Co=256
    set noshowmode
'''

[[plugins]] # lightline-theme
repo = 'delphinus/lightline-delphinus'
depends = ['lightline.vim']
hook_add = '''
    let g:lightline_delphinus_colorscheme = 'solarized_improved'
'''

[[plugins]] # display buffer on tabline
repo = 'ap/vim-buftabline'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]] # visible indent
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_faster = 1
    let g:indentLine_concealcursor = ''
    let g:indentLine_fileTypeExclude = ['help', 'denite']
'''

[[plugins]] # japanese help
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'kana/vim-textobj-user'
hook_add = 'source ~/.vim/rc/plugins/vim-textobj-user.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
    xmap <CR> <Plug>(LiveEasyAlign)
'''

[[plugins]] # completion
repo = 'cohama/lexima.vim'
hook_add = '''
    let g:lexima_map_escape = 'jj'
    inoremap <C-f> <C-r>=lexima#insmode#leave(1, '<LT>C-G>U<LT>RIGHT>')<CR>
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'

# ---------- Git plugins ----------
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    set signcolumn=yes " Show gitgutter column always
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    nmap [fugitive] <Nop>
    map  [Space]g [fugitive]
    nmap <silent> [fugitive]s :<C-u>Gstatus<CR>
    nmap <silent> [fugitive]d :<C-u>Gdiff<CR>
    nmap <silent> [fugitive]b :<C-u>Gblame<CR>
    nmap <silent> [fugitive]l :<C-u>Glog<CR>
'''

# ---------- Syntax ----------
[[plugins]] # for deoplete
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]] # for deoplete
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]] # linter
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_set_highlights = 0
    " エラー行に表示するマーク
    let g:ale_sign_error = '✗'
    let g:ale_sign_warning = '!'
    highlight link ALEErrorSign ErrorMsg
    highlight link ALEWarningSign Search
    " エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
    let g:ale_echo_msg_format = '[%linter%] %code: %%s [%severity%]'
    " エラー表示の列を常時表示
    let g:ale_sign_column_always = 1
    " ステータスラインに情報を表示
    let g:ale_statusline_format = [
    \   g:ale_sign_error . ' %d',
    \   g:ale_sign_warning . ' %d',
    \   '✓']

    " ファイルを開いたときにlint実行
    let g:ale_lint_on_enter = 1
    " ファイルを保存したときにlint実行
    let g:ale_lint_on_save = 1
    " 編集中のlintはしない
    let g:ale_lint_on_text_changed = 0
    " 有効にするlinter
    let g:ale_linters = {
    \   'sh': ['language_server'],
    \   'python': ['flake8'],
    \   'R': ['lintr'],
    \}

    " ファイルを保存したときにfix実行
    let g:ale_fix_on_save = 1
    " 有効にするfixer
    let g:ale_fixers = {
    \   '*': ['remove_trailing_lines', 'trim_whitespace'],
    \   'python': ['black'],
    \}
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
hook_add = '''
    let g:precious_enable_switchers = {
    \   "*" : {
    \       "setfiletype" : 0
    \   },
    \   "vim" : {
    \       "setfiletype" : 1
    \   },
    \   "toml" : {
    \       "setfiletype" : 1
    \   },
    \}
    let g:precious_enable_switch_CursorMoved = {
    \   "*" : 1,
    \   "help" : 0,
    \}
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'
