# ---------- Essential -----------
[[plugins]] # plugin manager
repo = 'Shougo/dein.vim'

[[plugins]] # most recent use
repo = 'Shougo/neomru.vim'

# ---------- Useful plugins ----------
[[plugins]] # smart f
repo = 'rhysd/clever-f.vim'

[[plugins]] # smart f
repo = 'tpope/vim-repeat'

# [[plugins]] # add text object
# repo = 'kana/vim-textobj-user'
# hook_add = 'source ~/.vim/rc/plugins/vim-textobj-user.vim'

[[plugins]] # add vim operator
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
    xmap <CR> <Plug>(LiveEasyAlign)
'''

[[plugins]] # bracket completion
repo = 'cohama/lexima.vim'
hook_add = '''
    let g:lexima_map_escape = 'jj'
'''

[[plugins]] # bracket completion
repo = 'jiangmiao/auto-pairs'
hook_add = '''
  inoremap <silent> <C-l> <C-g>u<C-r>=AutoPairsFastWrap()<CR>
  let g:AutoPairsMapCh = 0
'''

[[plugins]] # faster jk
repo = 'rhysd/accelerated-jk'
hook_add = '''
    nmap <silent>j <Plug>(accelerated_jk_gj)
    nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'tyru/columnskip.vim'
hook_add = '''
  nmap sj <Plug>(columnskip-j)
  nmap sk <Plug>(columnskip-k)
  omap sj <Plug>(columnskip-j)
  xmap sk <Plug>(columnskip-k)
  xmap sj <Plug>(columnskip-j)
  omap sk <Plug>(columnskip-k)
'''

[[plugins]]
repo = 'kana/vim-niceblock'
hook_add = '''
    xmap I  <Plug>(niceblock-I)
    xmap A  <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
hook_add = '''
    nmap R <Plug>(operator-replace)
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
hook_add = '''
    nmap <silent>sa <Plug>(operator-surround-append)a
    nmap <silent>sd <Plug>(operator-surround-delete)a
    nmap <silent>sr <Plug>(operator-surround-replace)a
'''

[[plugins]]
repo = 'osyo-manga/vim-jplus'
hook_add = '''
    nmap J <Plug>(jplus)
'''

[[plugins]] # commentout
repo = 'tyru/caw.vim'
hook_add = '''
    let g:caw_no_default_keymappings = 1
    let g:caw_dollarpos_sp_left = ' '
    nmap <silent> gc <Plug>(caw:hatpos:toggle)
    nmap <silent> ga <Plug>(caw:dollarpos:comment)
    nmap <silent> go <Plug>(caw:jump:comment-next)
    nmap <silent> gO <Plug>(caw:jump:comment-prev)
    xmap <silent> gc <Plug>(caw:hatpos:toggle)
    xmap <silent> ga <Plug>(caw:dollarpos:comment)
    xmap <silent> go <Plug>(caw:jump:comment-next)
    xmap <silent> gO <Plug>(caw:jump:comment-prev)
'''
