[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
hook_add = '''
  xmap I  <Plug>(niceblock-I)
  xmap A  <Plug>(niceblock-A)
'''

[[plugins]]

[[plugins]]
repo = 'machakann/vim-sandwich'
on_map = {nx = '<Plug>'}
hook_add = '''
  let g:sandwich_no_default_key_mappings             = 1
  let g:textobj_functioncall_no_default_key_mappings = 1
  let g:sandwich#recipes = deepcopy(g:sandwich#default_recipes)
'''
