return{}
-- {"nvim-treesitter/nvim-treesitter", event = "BufNewFile, BufRead"},
-- 
-- --disable default plugins
--   performance = {
--     rtp = {
--       disable_plugins = {
--         'netrw',
--         'netrwPlugin',
--         'netrwSettings',
--         'netrwFileHandlers',
--         'gzip',
--         'zip',
--         'zipPlugin',
--         'tar',
--         'tarPlugin',
--         'getscript',
--         'getscriptPlugin',
--         'vimball',
--         'vimballPlugin',
--         '2html_plugin',
--         'logipat',
--         'rrhelper',
--         'spellfile_plugin',
--         'sql_completion',
--       },
--     },
--   },
-- })
